# Generated by Django 5.1.7 on 2025-03-10 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_group_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='group',
        ),
    ]
