# Generated by Django 5.1.7 on 2025-03-10 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_employment_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='api.department'),
            preserve_default=False,
        ),
    ]
