# Generated by Django 5.1.7 on 2025-03-10 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_task_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_by',
            new_name='assigned_by',
        ),
    ]
