# Generated by Django 5.1.7 on 2025-03-10 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_created_by_task_assigned_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_by',
        ),
        migrations.AddField(
            model_name='task',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to='api.employment'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_user',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
