# Generated by Django 5.1.7 on 2025-03-10 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_task_assigned_by_task_create_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_user',
        ),
        migrations.AlterField(
            model_name='task',
            name='create_user',
            field=models.ForeignKey(blank=True, db_column='create_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to='api.employment'),
        ),
    ]
