# Generated by Django 5.1.7 on 2025-03-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_task_created_user_alter_task_create_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_user',
            field=models.CharField(db_column='create_user', default=1, max_length=255),
            preserve_default=False,
        ),
    ]
